# Generated by Django 4.2.7 on 2023-11-26 22:30

import URLSnip.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLSnip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.TextField(max_length=1000, validators=[URLSnip.models.validate_url]),
        ),
    ]
